repos:
- repo: local
  hooks:

  - id: ruff-check
    name: ruff-check
    entry: ruff check
    language: system
    types: [python]

  - id: ruff-format
    name: ruff-format
    entry: ruff format --check
    language: system
    types: [python]

  - id: pyre-check
    name: pyre-check
    entry: pyre
    language: system
    types: [python]
    pass_filenames: false

  - id: run-tests
    name: run-tests
    entry: bash -c 'cd $(git rev-parse --show-toplevel)/src/ && python -m unittest tests/*.py'
    language: system
    types: [python]
    pass_filenames: false
